### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by codeswholesale**

### CODE REVIEW

**Comment by JanGalek** [comment]
php 5.5 is not supported ;)

**Comment by codeswholesale** [comment]
What do you mean ;)?

**Comment by codeswholesale** [comment]
@JanGalek Changed to 5.6, thanks!

**Comment by JanGalek** [comment]
http://php.net/supported-versions.php php 5.5 isnt oficialy supported, so why required 5.5 >= ? :)

**Pull request merged**
